title: You can upload and download configurations via CloudSolrClient
type: added
authors:
- name: Alan Woodward
- name: Ishan Chattopadhyaya
links:
- name: SOLR-7125
  url: https://issues.apache.org/jira/browse/SOLR-7125
- name: SOLR-7158
  url: https://issues.apache.org/jira/browse/SOLR-7158
