title: Fixing Config API overlay property enabling or disabling the cache
type: fixed
authors:
- name: Sanjay Dutt
- name: hossman
- name: Eric Pugh
links:
- name: SOLR-17148
  url: https://issues.apache.org/jira/browse/SOLR-17148
