title: Set doAs param in ConfigurableInternodeAuthHadoopPlugin
type: fixed
authors:
- name: Geza Nagy
- name: Jason Gerlowski
- name: Mike Drob
links:
- name: SOLR-15233
  url: https://issues.apache.org/jira/browse/SOLR-15233
