title: When creating a configSet via the API, the "baseConfigSet" parameter now defaults
  to "_default".
type: added
authors:
- name: Amrit Sarkar
- name: David Smiley
links:
- name: SOLR-11861
  url: https://issues.apache.org/jira/browse/SOLR-11861
