title: Do not use docValues as stored for _str (copy)fields in _default configset
type: changed
authors:
- name: janhoy
links:
- name: SOLR-12350
  url: https://issues.apache.org/jira/browse/SOLR-12350
