title: SolrCoreParser now supports configuration of custom SpanQueryBuilder classes.
type: added
authors:
- name: Daniel Collins
- name: Christine Poerschke
links:
- name: SOLR-9933
  url: https://issues.apache.org/jira/browse/SOLR-9933
