= Codec Factory
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

A `codecFactory` can be specified in `solrconfig.xml` to determine which Lucene {lucene-javadocs}/core/org/apache/lucene/codecs/Codec.html[`Codec`] is used when writing the index to disk.

If not specified, Solr's `SchemaCodecFactory` is implicitly used as if it had been defined with no configuration options:

[source,xml]
----
<codecFactory class="solr.SchemaCodecFactory" />
----


== Available Codec Factories

=== solr.LuceneDefaultCodecFactory

The {solr-javadocs}/core/org/apache/solr/core/LuceneDefaultCodecFactory.html[`solr.LuceneDefaultCodecFactory`] Uses the Lucene {lucene-javadocs}/core/org/apache/lucene/codecs/Codec.html#getDefault()[`Codec.getDefault()`] and does not support any configuration options.

Example:

[source,xml]
----
<codecFactory class="solr.LuceneDefaultCodecFactory" />
----

=== solr.SchemaCodecFactory (default)

The {solr-javadocs}/core/org/apache/solr/core/SchemaCodecFactory.html[`solr.SchemaCodecFactory`] defaults to the same behavior as Lucene's default Codec, but supports 2 additional key features:

* Schema based per-fieldtype customizations:
** `docValuesFormat` and `postingsFormat` on any field type - see the xref:indexing-guide:field-type-definitions-and-properties.adoc#field-type-properties[Field Type Properties] section for more details.
** Support for `DenseVectorField` customizations to the `KnnVectorsFormat` - see the xref:query-guide:dense-vector-search.adoc[Dense Vector Search] section for more details.
* A `compressionMode` option:
** `BEST_SPEED` (default) is optimized for search speed performance
** `BEST_COMPRESSION` is optimized for disk space usage

Example:

[source,xml]
----
<codecFactory class="solr.SchemaCodecFactory">
  <str name="compressionMode">BEST_COMPRESSION</str>
</codecFactory>
----

=== solr.SimpleTextCodecFactory

This factory for Lucene's {solr-javadocs}/core/org/apache/solr/core/SimpleTextCodecFactory.html[`SimpleTextCodecFactory`] produces a plain text human-readable index format.

CAUTION: *FOR RECREATIONAL USE ONLY*.
This codec should never be used in production.
`SimpleTextCodec` is relatively slow and takes up a large amount of disk space.
Its use should be limited to educational and debugging purposes.

Example:

[source,xml]
----
<codecFactory class="solr.SimpleTextCodecFactory"/>
----
