= Property Substitution in Configuration Files
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// *TODO* merge this page with core-discovery.adoc?

Solr supports variable substitution of property values in configuration files, which allows runtime specification of various configuration options in `solrconfig.xml`.

The syntax is `${propertyname[:option default value]`}.
This allows defining a default that can be overridden when Solr is launched.
If a default value is not specified, then the property _must_ be specified at runtime or the configuration file will generate an error when parsed.

There are multiple methods for specifying properties that can be used in configuration files.
Of those below, strongly consider "config overlay" as the preferred approach, as it stays local to the configset and is easy to modify.

== JVM System Properties

Any JVM system property, usually specified using the `-D` flag when starting the JVM, can be used as variables in any XML configuration file in Solr.

For example, in the sample `solrconfig.xml` files, you will see this value which defines the locking type to use:

[source,xml]
----
<lockType>${solr.lock.type:native}</lockType>
----

Which means the lock type defaults to "native" but when starting Solr you could override this using a JVM system property by launching Solr with:

[source,bash]
----
bin/solr start -Dsolr.lock.type=none
----

In general, any Java system property that you want to set can be passed through the `bin/solr` script using the standard `-Dproperty=value` syntax.

Alternatively, you can add common system properties to the `SOLR_OPTS` environment variable defined in the Solr include file (`bin/solr.in.sh` or `bin/solr.in.cmd`).
For more information about how the Solr include file works, refer to: xref:deployment-guide:taking-solr-to-production.adoc[].

== Config API to Override solrconfig.xml

The xref:config-api.adoc[] allows you to use an API to modify Solr's configuration, specifically user defined properties.
Changes made with this API are stored in a file named `configoverlay.json`.
This file should only be edited with the API, but will look like this example:

[source,json]
----
{
  "userProps":{"update.autoCreateFields":"false"},
  "requestHandler":{"/myterms":{
      "name":"/myterms",
      "class":"solr.SearchHandler",
      "defaults":{
        "terms":true,
        "distrib":false},
      "components":["terms"]}}}
----

For more details, see the section xref:config-api.adoc[].

== User-Defined Properties in core.properties

Every Solr core has a `core.properties` file, automatically created when using the APIs.
When you create a SolrCloud collection, you can pass through custom parameters by prefixing the parameter name with `_property.name_` as a parameter.

For example, to add a property named "my.custom.prop":

[.dynamic-tabs]
--
[example.tab-pane#v1customprop]
====
[.tab-label]*V1 API*

[source,bash]
----
http://localhost:8983/solr/admin/collections?action=CREATE&name=gettingstarted&numShards=1&property.my.custom.prop=edismax
----
====

[example.tab-pane#v2]
====
[.tab-label]*V2 API*

[source,bash]
----
curl -X POST -H 'Content-type: application/json' -d '{"name": "gettingstarted", "numShards": 1, "properties": {"my.custom.prop": "edismax"}}' http://localhost:8983/api/collections
----
====
--

This will create a `core.properties` file that has at least the following properties (others omitted for brevity):

[source,properties]
----
#core.properties
name=gettingstarted
my.custom.prop=edismax
----

The `my.custom.prop` property can then be used as a variable, such as in `solrconfig.xml`:

[source,xml]
----
<requestHandler name="/select">
  <lst name="defaults">
    <str name="defType">${my.custom.prop}</str>
  </lst>
</requestHandler>
----

== Implicit Core Properties

Several attributes of a Solr core are available as "implicit" properties that can be used in variable substitution, independent of where or how the underlying value is initialized.

For example, regardless of whether the name for a particular Solr core is explicitly configured in `core.properties` or inferred from the name of the instance directory, the implicit property `solr.core.name` is available for use as a variable in that core's configuration file:

[source,xml]
----
<requestHandler name="/select">
  <lst name="defaults">
    <str name="collection_name">${solr.core.name}</str>
  </lst>
</requestHandler>
----

All implicit properties use the `solr.core.` name prefix, and reflect the runtime value of the equivalent xref:core-discovery.adoc[`core.properties` property]:

* `solr.core.name`
* `solr.core.config`
* `solr.core.schema`
* `solr.core.dataDir`
* `solr.core.transient`
* `solr.core.loadOnStartup`
