= Schema Factory Configuration
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr supports two styles of schema: a managed schema and a manually maintained `schema.xml` file.
When using a managed schema, features such as the xref:indexing-guide:schema-api.adoc[] and xref:indexing-guide:schemaless-mode.adoc[] are available.
When using `schema.xml`, the only way changes can be made to Solr's schema is by manually editing the file.

== <schemaFactory> in solrconfig.xml

The `<schemaFactory>` in `solrconfig.xml` defines whether your system will use a managed schema or `schema.xml`.

[source,xml]
----
<config>
  <schemaFactory>
    ...
  </schemaFactory>
</config>
----



While the "read" features of the Schema API are supported for all schema types, support for making schema modifications programmatically depends on the `<schemaFactory/>` in use.

== Schema Factories

=== ManagedIndexSchemaFactory

When a `<schemaFactory/>` is not explicitly declared in a `solrconfig.xml` file, Solr implicitly uses a `ManagedIndexSchemaFactory`, which is by default `"mutable"` (editable) and keeps schema information in a `managed-schema.xml` file.

Using the Managed Schema is required to be able to use the Schema API to modify your schema.
However, using Managed Schema does not mean you are also using Solr in Schemaless Mode (or "schema guessing" mode).

Schemaless mode requires enabling the Managed Schema if it is not already, but full schema guessing requires additional configuration as described in the section xref:indexing-guide:schemaless-mode.adoc[].

Below is an example of a `schemaFactory` that reflects Solr's defaults:

[source,xml]
----
  <schemaFactory class="ManagedIndexSchemaFactory">
    <bool name="mutable">true</bool>
    <str name="managedSchemaResourceName">managed-schema.xml</str>
  </schemaFactory>
----

The defaults can be overridden by explicitly configuring `ManagedIndexSchemaFactory` and changing one of the following options:

`mutable`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `true`
|===
+
Controls whether changes may be made to the schema data.
This must be set to `true` to allow edits to be made with the Schema API.
+
With the default configuration shown above, you could use the xref:indexing-guide:schema-api.adoc[] to modify the schema as much as you want, and then later change the value of `mutable` to `false` to "lock" the schema in place and prevent future changes.

`managedSchemaResourceName`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `managed-schema.xml`
|===
+
The name of the schema file.
The name can be anything other than `schema.xml`, as that name is reserved for the `ClassicIndexSchemaFactory`.

=== ClassicIndexSchemaFactory

An alternative to using a managed schema is to explicitly configure a `ClassicIndexSchemaFactory`.
This requires the use of a `schema.xml` file, and disallows any programatic changes to the Schema at run time.
The `schema.xml` file must be edited manually and is loaded only when the collection is loaded.

[source,xml]
----
  <schemaFactory class="ClassicIndexSchemaFactory"/>
----

This option takes no parameters.

== Changing Schema Factories

=== Switching from schema.xml to Managed Schema

If you have an existing Solr collection that uses `ClassicIndexSchemaFactory`, and you wish to convert to use a managed schema, you can simply modify the `solrconfig.xml` to specify the use of the `ManagedIndexSchemaFactory`.

Once Solr is restarted and it detects that a `schema.xml` file exists, but the `managedSchemaResourceName` file (i.e., "`managed-schema.xml`") does not exist, the existing `schema.xml` file will be renamed to `schema.xml.bak` and the contents re-written to the managed schema file.

If you look at the resulting file, you'll see this at the top of the page:

[source,xml]
----
<!-- Solr managed schema - automatically generated - DO NOT EDIT -->
----

You are now free to use the xref:indexing-guide:schema-api.adoc[] to make changes, and remove the `schema.xml.bak`.

=== Switching from Managed Schema to schema.xml

If you have started Solr with managed schema enabled and you would like to switch to manually editing a `schema.xml` file, you should take the following steps:

. Rename the `managed-schema.xml` file to `schema.xml`.
. Modify `solrconfig.xml` to replace the `schemaFactory` class.
.. Remove any `ManagedIndexSchemaFactory` definition if it exists.
.. Add a `ClassicIndexSchemaFactory` definition as shown above
. Reload the core(s).

If you are using SolrCloud, you may need to modify the files via ZooKeeper.
The `bin/solr` script provides an easy way to download the files from ZooKeeper and upload them back after edits.
See the section xref:deployment-guide:solr-control-script-reference.adoc#zookeeper-operations[ZooKeeper Operations] for more information.

[TIP]
====
To have full control over your `schema.xml` file, you may also want to disable schema guessing, which allows unknown fields to be added to the schema during indexing.
The properties that enable this feature are discussed in the section xref:indexing-guide:schemaless-mode.adoc[].
====
