title: 'Fixed a bug preventing Config API set properties (aka: configoverlay.json)
  from being used in config file property substitution'
type: fixed
authors:
- name: hossman
links:
- name: SOLR-17834
  url: https://issues.apache.org/jira/browse/SOLR-17834
