# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

github:
  description: "Apache Solr open-source search software"
  homepage: https://solr.apache.org/
  labels:
    - lucene
    - solr
    - search
    - nosql
    - java
    - backend
    - search-engine
    - information-retrieval

  enabled_merge_buttons:
    squash: true
    merge:  false
    rebase: false

  # TODO: Add to this list for each new minor release
  protected_branches:
    main: {}
    branch_9_0: {}
    branch_9_1: {}
    branch_9_2: {}
    branch_9_3: {}
    branch_9_4: {}
    branch_9_5: {}
    branch_9x: {}

  protected_tags:
    - "releases/*"

  autolink_jira:
    - SOLR

  collaborators:
    - solrbot

notifications:
  commits:      commits@solr.apache.org
  issues:       issues@solr.apache.org
  pullrequests: issues@solr.apache.org
  jira_options: link label worklog
