# This file can configure Lift PR static analysis. 
# Docs for adding, removing or changing checks can be found here:
# https://help.sonatype.com/lift/configuration-reference

jdkVersion = "11"
disableTools = [ "refactor-first" ]
ignoreFiles = '''
**/test/**
**/*.min.js
solr/webapp/web/libs/*.js
'''
build = "./gradlew jar"
