title: Configuring slowQueryThresholdMillis logs slow requests to a separate file
  - solr_slow_requests.log.
type: added
authors:
- name: Shawn Heisey
- name: Remko Popma
- name: Varun Thacker
links:
- name: SOLR-11453
  url: https://issues.apache.org/jira/browse/SOLR-11453
