title: Add auto hard-commit settings based on tlog size
type: added
authors:
- name: Rupa Shankar
- name: Anshum Gupta
links:
- name: SOLR-11277
  url: https://issues.apache.org/jira/browse/SOLR-11277
