title: Configsets now include a `minPrefixQueryTermLength` setting, which instructs
  Solr to reject prefix queries whose prefixes are "too short". This can be used as
  one line of defense against "runaway wildcard queries" consuming too many resources.
  The setting is disabled ('-1') in the default configset but can be overridden with
  a property ('solr.query.minPrefixLength'). Users may also override their collection-wide
  setting for individual queries by providing a `minPrefixQueryTermLength` local-param.
type: added
authors:
- name: Jason Gerlowski
- name: David Smiley
links:
- name: SOLR-17195
  url: https://issues.apache.org/jira/browse/SOLR-17195
