title: Fixed performance regression of misconfigured threadpools from SOLR-16879 (Solr
  9.4). Shard splits and concurrent/large collection backup/restore performance was
  serial. UpdateLog replay was a little suboptimal in thread usage too.
type: fixed
authors:
- name: Pierre Salagnac
- name: Hakan Özler
- name: David Smiley
links:
- name: SOLR-17391
  url: https://issues.apache.org/jira/browse/SOLR-17391
- name: SOLR-16879
  url: https://issues.apache.org/jira/browse/SOLR-16879
