title: Restore ability to configure tlog directory. Changes largely focus on UpdateLog
  and HdfsUpdateLog. There is no anticipated change in existing behavior, other than
  that the `dir` parameter to the `&lt;updateLog&gt;` element in `solrconfig.xml`,
  which has long been silently ignored, will now be respected
type: fixed
authors:
- name: Michael Gibney
- name: David Smiley
links:
- name: SOLR-16962
  url: https://issues.apache.org/jira/browse/SOLR-16962
