title: Adding support for uploading zipped configsets using ConfigSets API
type: added
authors:
- name: Varun Rajput
- name: Ishan Chattopadhyaya
- name: Noble Paul
- name: Anshum Gupta
- name: Gregory Chanan
links:
- name: SOLR-6736
  url: https://issues.apache.org/jira/browse/SOLR-6736
