title: Update Solr default/example and test configs to use WordDelimiterGraphFilterFactory.
type: other
authors:
- name: Steve Rowe
links:
- name: SOLR-10344
  url: https://issues.apache.org/jira/browse/SOLR-10344
