= Exercise 6: Using Learned Sparse Retrieval (LSR)
:experimental:
:tabs-sync-option:
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[[exercise-6]]
== Exercise 6: Using Learned Sparse Retrieval (LSR) in Solr

...

https://en.wikipedia.org/wiki/Learned_sparse_retrieval[Learned sparse retrieval]

...

=== Getting Ready

[,console]
----
bin/solr start -noprompt -e cloud
----

...

[,console]
----
bin/solr create -c buzz
----


=== Placeholder section with draft content

terminology? -- transparent? explainable? interpretable? -- why did this document (not) match? why did this document get this score? why did document X score higher than document Y?

Somewhat == can explain why document got the score but can less so explain why the term weights are what they are


[cols=",,,,,",options="header",]
|===
|Approach                        |transparent w.r.t. match |term expansion |term weights |transparent w.r.t. score |Large Language Model involved
|?lexical?                       |Yes                      |No             |No           |Yes                      |No
|?lexical? with curated synonyms |Yes                      |Yes            |if curated   |Yes                      |No
|learned sparse                  |Yes                      |Yes            |learned      |Somewhat                 |Yes
|dense vector                    |No                       |n/a            |n/a          |No                       |Yes
|===

terminology? -- value? weight? score? something else?

[cols=",,,,",options="header",]
|===
|Approach                            |Value Indexed |Value Retrievable |Value Storage Precision |Extra(?) data structure since not internally encoded as term frequency
|raw term frequency similarity field |Yes           |Yes               |Y                       |N
|payloaded fields                    |Yes           |Yes               |Y                       |Y
|(plain) rank fields                 |Yes           |No                |No                      |N
|(opaque) rank fields                |Yes           |No                |No                      |N
|===


=== Indexing

...

[,console]
----
bin/solr post -c buzz example/exampledocs/three_bees.json
----

=== Searching

...


[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=text_ws:bee'
----

As can be seen the scores are the same for all documents.

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.06069608
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.06069608
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.06069608
    }]
...
```

=== Searching with the raw term frequency similarity field

...

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=text_drtf:bee'
----

As can be seen the scores are as supplied after the pipe delimiter for the `bee` term.

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":3.0
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":3.0
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":3.0
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=text_drtf:(honey+bee)'
----

As can be seen the scores are as supplied after the pipe delimiter, summed for the matching terms.

```
...
    "docs":[{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":5.0
    },{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":3.0
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":3.0
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=text_drtf:(bumble^10+honey^2+bee)'
----

As can be seen the scores are as supplied after the pipe delimiter, summed for the matching terms and boosted as per the query.


```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":23.0
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":7.0
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":3.0
    }]
...
```

=== Searching with payloaded fields

...

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!payload_score+f=text_dpf+func=sum+operator=or\}bee'
----

As can be seen the scores are as supplied after the pipe delimiter for the `bee` term.

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.3
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.3
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.3
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!payload_score+f=text_dpf+func=sum+operator=or\}honey+bee'
----

As can be seen the scores are as supplied after the pipe delimiter, summed for the matching terms.

```
...
    "docs":[{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.5
    },{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.3
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.3
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!bool+should=$ref\}&ref=\{!boost+b=10\}\{!payload_score+f=text_dpf+func=sum+operator=or\}bumble&ref=\{!boost+b=2\}\{!payload_score+f=text_dpf+func=sum+operator=or\}honey&ref=\{!payload_score+f=text_dpf+func=sum+operator=or\}bee'
----

As can be seen the scores are as supplied after the pipe delimiter, summed for the matching terms and boosted as per the query.


```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":2.3
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.70000005
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.3
    }]
...
```

=== Searching with (plain) rank fields

...

It is implementation detail and perhaps therefore not mentioned in the {solr-javadocs}/core/org/apache/solr/schema/RankField.html[RankField javadocs] but multiple (Solr) rank fields map to the same underlying (Lucene) feature field.

As can be seen in the scores below and as mentioned in the {lucene-javadocs}/core/org/apache/lucene/document/FeatureField.html[FeatureField javadocs] there is some loss of precision for storage efficiency, but as with the 'raw term frequency similarity' field above the feature values are internally encoded as term frequencies.

...

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!rank+f=bee_rank+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.2998047
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.2998047
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!bool+should=$ref\}&ref=\{!rank+f=honey_rank+function=linear\}&ref=\{!rank+f=bee_rank+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.49951172
    },{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.2998047
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!bool+should=$ref\}&ref=\{!rank+f=bumble_rank+weight=10+function=linear\}&ref=\{!rank+f=honey_rank+weight=2+function=linear\}&ref=\{!rank+f=bee_rank+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":2.296875
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.69921875
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

=== Searching with (opaque) rank fields

...

... TODO: 'plain' and 'opaque' is not the right terminology to use here ...


 * plain: alone bee bumble flower food honey nature solitary sugar

 * opaque: 1 2 3 4 5 6 7 8 9

 * mapping: alone=1 bee=2 bumble=3 flower=4 food=5 honey=6 nature=7 solitary=8 sugar=9

...

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!rank+f=lsr_term2+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.2998047
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.2998047
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!bool+should=$ref\}&ref=\{!rank+f=lsr_term6+function=linear\}&ref=\{!rank+f=lsr_term2+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.49951172
    },{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":0.2998047
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

[,console]
----
curl 'http://localhost:8983/solr/buzz/select?fl=text_*,score&q=\{!bool+should=$ref\}&ref=\{!rank+f=lsr_term3+weight=10+function=linear\}&ref=\{!rank+f=lsr_term6+weight=2+function=linear\}&ref=\{!rank+f=lsr_term2+function=linear\}'
----

```
...
    "docs":[{
      "text_ws":"bumble bee",
      "text_dpf":"bee|0.3 bumble|0.2",
      "text_drtf":"bee|3 bumble|2",
      "score":2.296875
    },{
      "text_ws":"honey bee",
      "text_dpf":"bee|0.3 honey|0.2 sugar|0.1",
      "text_drtf":"bee|3 honey|2 sugar|1",
      "score":0.69921875
    },{
      "text_ws":"solitary bee",
      "text_dpf":"bee|0.3 solitary|0.2 alone|0.1",
      "text_drtf":"bee|3 solitary|2 alone|1",
      "score":0.2998047
    }]
...
```

=== Searching with ??? fields

...
