title: Allowing configuring maxMergeSizeMB and maxCachedMB when using NRTCachingDirectoryFactory.
type: added
authors:
- name: Andy Laird
- name: Mark Miller
links:
- name: SOLR-3531
  url: https://issues.apache.org/jira/browse/SOLR-3531
