title: Support configuring IndexWriter max thread count in solrconfig.
type: added
authors:
- name: phunt
- name: Mark Miller
links:
- name: SOLR-3929
  url: https://issues.apache.org/jira/browse/SOLR-3929
