title: JSON update format - "null" field values are now dropped instead of causing
  an exception.
type: added
authors:
- name: Trygve Laugstøl
- name: yonik
links:
- name: SOLR-2714
  url: https://issues.apache.org/jira/browse/SOLR-2714
