title: Sync up basic_configs and data_driven_schema_configs, removing almost all differences
  except what is required for schemaless.
type: other
authors:
- name: yonik
links:
- name: SOLR-9163
  url: https://issues.apache.org/jira/browse/SOLR-9163
