title: Allow configurable index deletion policy and provide a default implementation
  which allows deletion of commit points on various criteria such as number of commits,
  age of commit point and optimized status. See http://lucene.apache.org/java/2_3_2/api/org/apache/lucene/index/IndexDeletionPolicy.html
type: added
authors:
- name: yonik
- name: Noble Paul
- name: Akshay Ukey
- name: shalin
links:
- name: SOLR-617
  url: https://issues.apache.org/jira/browse/SOLR-617
