title: Add configurable IndexReaderFactory so that alternate IndexReader implementations
  can be specified via solrconfig.xml. Note that using a custom IndexReader may be
  incompatible with ReplicationHandler (see comments in SOLR-1366). This should be
  treated as an experimental feature.
type: added
authors:
- name: Andrzej Bialecki
- name: hossman
- name: Mark Miller
- name: John Wang
links:
- name: SOLR-243
  url: https://issues.apache.org/jira/browse/SOLR-243
- name: SOLR-1366
  url: https://issues.apache.org/jira/browse/SOLR-1366
