title: Allow access to DataImporter and DIHConfiguration from DataImportHandler.
type: other
authors:
- name: Aaron LaBella
- name: shalin
links:
- name: SOLR-6194
  url: https://issues.apache.org/jira/browse/SOLR-6194
