title: JettySolrRunner QueuedThreadPool's configuration code is never executed.
type: fixed
authors:
- name: dweiss
- name: shalin
links:
- name: SOLR-6208
  url: https://issues.apache.org/jira/browse/SOLR-6208
