title: Make discarding punctuation configurable in JapaneseTokenizerFactory. The default
  is to discard punctuation, but this is overridable as an expert option.
type: other
authors:
- name: Kazuaki Hiraga
- name: Jun Ohtani
links:
- name: SOLR-3524
  url: https://issues.apache.org/jira/browse/SOLR-3524
