title: DIH no longer requires the "config" parameter to be specified in solrconfig.xml.
  Instead, the configuration is loaded and parsed with every import. This allows the
  use of a different configuration with each import, and makes correcting configuration
  errors simpler. Also, the configuration itself can be passed using the "dataConfig"
  parameter rather than using a file (this previously worked in debug mode only).
  When configuration errors are encountered, the error message is returned in XML
  format.
type: other
authors:
- name: James Dyer
links:
- name: SOLR-2115
  url: https://issues.apache.org/jira/browse/SOLR-2115
