title: Proper error reporting if updateLog is configured w/o necessary "_version_"
  field in schema.xml
type: fixed
authors:
- name: hossman
links:
- name: SOLR-3746
  url: https://issues.apache.org/jira/browse/SOLR-3746
