= Dense Vector Search
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr's *Dense Vector Search* adds support for indexing and searching dense numerical vectors.

https://en.wikipedia.org/wiki/Deep_learning[Deep learning] can be used to produce a vector representation of both the query and the documents in a corpus of information.

These neural network-based techniques are usually referred to as neural search, an industry derivation from the academic field of https://www.microsoft.com/en-us/research/uploads/prod/2017/06/fntir2018-neuralir-mitra.pdf[Neural information Retrieval].

== Important Concepts

=== Dense Vector Representation
A traditional tokenized https://en.wikipedia.org/wiki/Inverted_index[inverted index] can be considered to model text as a "sparse" vector, in which each term in the corpus corresponds to one vector dimension. In such a model, the number of dimensions is generally quite high (corresponding to the term dictionary cardinality), and the vector for any given document contains mostly zeros (hence it is sparse, as only a handful of terms that exist in the overall index will be present in any given document).

Dense vector representation contrasts with term-based sparse vector representation in that it distills approximate semantic meaning into a fixed (and limited) number of dimensions.

The number of dimensions in this approach is generally much lower than the sparse case, and the vector for any given document is dense, as most of its dimensions are populated by non-zero values.

In contrast to the sparse approach (for which tokenizers are used to generate sparse vectors directly from text input) the task of generating vectors must be handled in application logic external to Apache Solr.

There may be cases where it makes sense to directly search data that natively exists as a vector (e.g., scientific data); but in a text search context, it is likely that users will leverage deep learning models such as https://en.wikipedia.org/wiki/BERT_(language_model)[BERT] to encode textual information as dense vectors, supplying the resulting vectors to Apache Solr explicitly at index and query time.

For additional information you can refer to this https://sease.io/2021/12/using-bert-to-improve-search-relevance.html[blog post].

=== Dense Retrieval
Given a dense vector `v` that models the information need, the easiest approach for providing dense vector retrieval would be to calculate the distance (euclidean, dot product, etc.) between `v` and each vector `d` that represents a document in the corpus of information.

This approach is quite expensive, so many approximate strategies are currently under active research.

The strategy implemented in Apache Lucene and used by Apache Solr is based on Navigable Small-world graph.

It provides efficient approximate nearest neighbor search for high dimensional vectors.

See https://doi.org/10.1016/j.is.2013.10.006[Approximate nearest neighbor algorithm based on navigable small world graphs [2014]] and https://arxiv.org/abs/1603.09320[Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs [2018]] for details.


== Index Time
This is the Apache Solr field type designed to support dense vector search:

=== DenseVectorField
The dense vector field gives the possibility of indexing and searching dense vectors of float elements.

For example:

`[1.0, 2.5, 3.7, 4.1]`

Here's how `DenseVectorField` should be configured in the schema:

[source,xml]
<fieldType name="knn_vector" class="solr.DenseVectorField" vectorDimension="4" similarityFunction="cosine"/>
<field name="vector" type="knn_vector" indexed="true" stored="true"/>

`vectorDimension`::
+
[%autowidth,frame=none]
|===
s|Required |Default: none
|===
+
The dimension of the dense vector to pass in.
+
Accepted values:
Any integer.

`similarityFunction`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `euclidean`
|===
+
Vector similarity function; used in search to return top K most similar vectors to a target vector.
+
Accepted values: `euclidean`, `dot_product`  or `cosine`.

* `euclidean`: https://en.wikipedia.org/wiki/Euclidean_distance[Euclidean distance]
* `dot_product`: https://en.wikipedia.org/wiki/Dot_product[Dot product]

[NOTE]
this similarity is intended as an optimized way to perform cosine similarity. In order to use it, all vectors must be of unit length, including both document and query vectors. Using dot product with vectors that are not unit length can result in errors or poor search results.

* `cosine`: https://en.wikipedia.org/wiki/Cosine_similarity[Cosine similarity]

[NOTE]
the preferred way to perform cosine similarity is to normalize all vectors to unit length, and instead use DOT_PRODUCT. You should only use this function if you need to preserve the original vectors and cannot normalize them in advance.

To use the following advanced parameters that customise the codec format
and the hyperparameter of the HNSW algorithm, make sure the xref:configuration-guide:codec-factory.adoc[Schema Codec Factory], is in use.

Here's how `DenseVectorField` can be configured with the advanced hyperparameters:

[source,xml]
<fieldType name="knn_vector" class="solr.DenseVectorField" vectorDimension="4" similarityFunction="cosine" knnAlgorithm="hnsw" hnswMaxConnections="10" hnswBeamWidth="40"/>
<field name="vector" type="knn_vector" indexed="true" stored="true"/>

`knnAlgorithm`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `hnsw`
|===
+
(advanced) Specifies the underlying knn algorithm to use
+

Accepted values: `hnsw`.

Please note that the `knnAlgorithm` accepted values may change in future releases.

`vectorEncoding`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `FLOAT32`
|===
+
(advanced) Specifies the underlying encoding of the dense vector elements. This affects memory/disk impact for both the indexed and stored fields (if enabled)
+

Accepted values: `FLOAT32`, `BYTE`.


`hnswMaxConnections`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `16`
|===
+
(advanced) This parameter is specific for the `hnsw` knn algorithm:
+
Controls how many of the nearest neighbor candidates are connected to the new node.
+
It has the same meaning as `M` from the 2018 paper.
+
Accepted values:
Any integer.

`hnswBeamWidth`::
+
[%autowidth,frame=none]
|===
|Optional |Default: `100`
|===
+
(advanced) This parameter is specific for the `hnsw` knn algorithm:
+
It is the number of nearest neighbor candidates to track while searching the graph for each newly inserted node.
+
It has the same meaning as `efConstruction` from the 2018 paper.
+
Accepted values:
Any integer.

`DenseVectorField` supports the attributes: `indexed`, `stored`.

[NOTE]
currently multivalue is not supported

Here's how a `DenseVectorField` should be indexed:

[.dynamic-tabs]
--
[example.tab-pane#json]
====
[.tab-label]*JSON*
[source,json]
----
[{ "id": "1",
"vector": [1.0, 2.5, 3.7, 4.1]
},
{ "id": "2",
"vector": [1.5, 5.5, 6.7, 65.1]
}
]
----
====

[example.tab-pane#xml]
====
[.tab-label]*XML*
[source,xml]
----
<add>
<doc>
<field name="id">1</field>
<field name="vector">1.0</field>
<field name="vector">2.5</field>
<field name="vector">3.7</field>
<field name="vector">4.1</field>
</doc>
<doc>
<field name="id">2</field>
<field name="vector">1.5</field>
<field name="vector">5.5</field>
<field name="vector">6.7</field>
<field name="vector">65.1</field>
</doc>
</add>
----
====

[example.tab-pane#solrj]
====
[.tab-label]*SolrJ*
[source,java,indent=0]
----
final SolrClient client = getSolrClient();

final SolrInputDocument d1 = new SolrInputDocument();
d1.setField("id", "1");
d1.setField("vector", Arrays.asList(1.0f, 2.5f, 3.7f, 4.1f));


final SolrInputDocument d2 = new SolrInputDocument();
d2.setField("id", "2");
d2.setField("vector", Arrays.asList(1.5f, 5.5f, 6.7f, 65.1f));

client.add(Arrays.asList(d1, d2));
----
====
--

== Query Time

Apache Solr provides two query parsers that work with dense vector fields, that each support differnet ways of matching documents based on vector similarity: The `knn` query parser, and the `vecSim` query parser.

Both parsers return scores for retrieved documents that is the approximate distance to the target vector (defined by the similarityFunction configured at indexing time) and both support "Pre-Filtering" the document graph to reduce the number of candidate vectors evaluated (with out needing to compute their vector similarity distances).

Common parameters for both query parsers are:

`f`::
+
[%autowidth,frame=none]
|===
s|Required |Default: none
|===
+
The `DenseVectorField` to search in.

`preFilter`::
+
[%autowidth,frame=none]
|===
|Optional |Default: Depends on usage, see below.
|===
+
Specifies an explicit list of Pre-Filter query strings to use.

`includeTags`::
+
[%autowidth,frame=none]
|===
|Optional |Default: none
|===
+
Indicates that only `fq` filters with the specified `tag` should be considered for implicit Pre-Filtering.  Must not be combined with `preFilter`.


`excludeTags`::
+
[%autowidth,frame=none]
|===
|Optional |Default: none
|===
+
Indicates that `fq` filters with the specified `tag` should be excluded from consideration for implicit Pre-Filtering.  Must not be combined with `preFilter`.


=== knn Query Parser

The `knn` k-nearest neighbors query parser matches k-nearest documents to the target vector.

In addition to the common parameters described above, it takes the following parameters:

`topK`::
+
[%autowidth,frame=none]
|===
|Optional |Default: 10
|===
+
How many k-nearest results to return.

Here's an example of a simple `knn` search:

[source,text]
?q={!knn f=vector topK=10}[1.0, 2.0, 3.0, 4.0]

The search results retrieved are the k=10 nearest documents to the vector in input `[1.0, 2.0, 3.0, 4.0]`, ranked by the `similarityFunction` configured at indexing time.

=== vecSim Query Parser

The `vecSim` vector similarity query parser matches documents whose similarity with the target vector is a above a minimum threshold.

In addition to the common parameters described above, it takes the following parameters:


`minReturn`::
+
[%autowidth,frame=none]
|===
s|Required |Default: none
|===
+
Minimum similarity threshold of nodes in the graph to be returned as matches

`minTraverse`::
+
[%autowidth,frame=none]
|===
|Optional |Default: -Infinity
|===
+
Minimum similarity of nodes in the graph to continue traversal of their neighbors

Here's an example of a simple `vecSim` search:

[source,text]
?q={!vecSim f=vector minReturn=0.7}[1.0, 2.0, 3.0, 4.0]

The search results retrieved are all documents whose similarity with the input vector `[1.0, 2.0, 3.0, 4.0]` is at least `0.7` based on the `similarityFunction` configured at indexing time


=== Graph Pre-Filtering

Pre-Filtering the set of candidate documents considered when walking the graph can be specified either explicitly, or implicitly (based on existing `fq` params) depending on how and when these dense vector query parsers are used.

==== Explicit Pre-Filtering

The `preFilter` parameter can be specified explicitly to reduce the number of candidate documents evaluated for the distance calculation:

[source,text]
?q={!vecSim f=vector minReturn=0.7 preFilter=inStock:true}[1.0, 2.0, 3.0, 4.0]

In the above example, only documents matching the Pre-Filter `inStock:true` will be candidates for consideration when evaluating the `knn` search against the specified vector.

The `preFilter` parameter may be blank (ex: `preFilter=""`) to indicate that no Pre-Filtering should be performed; or it may be multi-valued -- either through repetition, or via duplicated xref:local-params.adoc#parameter-dereferencing[Parameter References].

These two examples are equivalent:

[source,text]
?q={!knn f=vector topK=10 preFilter=category:AAA preFilter=inStock:true}[1.0, 2.0, 3.0, 4.0]

[source,text]
----
?q={!knn f=vector topK=10 preFilter=$knnPreFilter}[1.0, 2.0, 3.0, 4.0]
&knnPreFilter=category:AAA
&knnPreFilter=inStock:true
----

==== Implicit Pre-Filtering

While the `preFilter` parameter may be explicitly specified on *_any_* usage of the `knn` or `vecSim` query parsers, the default Pre-Filtering behavior (when no `preFilter` parameter is specified) will vary based on how the query parser is used:

* When used as the main `q` param: `fq` filters in the request (that are not xref:common-query-parameters.adoc#cache-local-parameter[Solr Post Filters]) will be combined to form an implicit Graph Pre-Filter.
** This default behavior optimizes the number of vector distance calculations considered, eliminating documents that would eventually be excluded by an `fq` filter anyway.
** `includeTags` and `excludeTags` may be used to limit the set of `fq` filters used in the Pre-Filter.
* When a vector search query parser is used as an `fq` param, or as a subquery clause in a larger query: No implicit Pre-Filter is used.
** `includeTags` and `excludeTags` must not be used in these situations.


The example request below shows two usages of vector query parsers that will get _no_ implicit Pre-Filtering from any of the `fq` parameters, because neither usage is as the main `q` param:

[source,text]
----
?q=(color_str:red OR {!vecSim f=color_vector minReturn=0.7 v="[1.0, 2.0, 3.0, 4.0]"})
&fq={!knn f=title_vector topK=10}[9.0, 8.0, 7.0, 6.0]
&fq=inStock:true
----


However, the next example shows a basic request where all `fq` parameters will be used as implicit Pre-Filters on the main `knn` query:

[source,text]
----
?q={!knn f=vector topK=10}[1.0, 2.0, 3.0, 4.0]
&fq=category:AAA
&fq=inStock:true
----

If we modify the above request to add tags to the `fq` parameters, we can specify an `includeTags` option on the `knn` parser to limit which `fq` filters are used for Pre-Filtering:

[source,text]
----
?q={!knn f=vector topK=10 includeTags=for_knn}[1.0, 2.0, 3.0, 4.0]
&fq=category:AAA
&fq={!tag=for_knn}inStock:true
----

In this example, only the `inStock:true` filter will be used for Pre-Filtering to find the the `topK=10` documents, and the `category:AAA` filter will be applied independently; possibly resulting in less then 10 total matches.


Some use cases where `includeTags` and/or `excludeTags` may be more useful then an explicit `preFilter` parameters:

* You have some `fq` parameters that are xref:configuration-guide:requesthandlers-searchcomponents.adoc#paramsets-and-useparams[re-used on many requests] (even when you don't use search dense vector fields) that you wish to be used as Pre-Filters when you _do_ search dense vector fields.
* You typically want all `fq` params to be used as graph Pre-Filters on your `knn` queries, but when users "drill down" on Facets, you want the `fq` parameters you add to be excluded from the Pre-Filtering so that the result set gets smaller; instead of just computing a new `topK` set.



=== Usage in Re-Ranking Query

Both dense vector search query parsers can be used to rerank first pass query results:

[source,text]
&q=id:(3 4 9 2)&rq={!rerank reRankQuery=$rqq reRankDocs=4 reRankWeight=1}&rqq={!knn f=vector topK=10}[1.0, 2.0, 3.0, 4.0]


[IMPORTANT]
====
When using `knn` in re-ranking pay attention to the `topK` parameter.

The second pass score(deriving from knn) is calculated only if the document `d` from the first pass is within
the k-nearest neighbors(*in the whole index*) of the target vector to search.

This means the second pass `knn` is executed on the whole index anyway, which is a current limitation.

The final ranked list of results will have the first pass score(main query `q`) added to the second pass score(the approximated similarityFunction distance to the target vector to search) multiplied by a multiplicative factor(reRankWeight).

Details about using the ReRank Query Parser can be found in the xref:query-guide:query-re-ranking.adoc[Query Re-Ranking] section.
====

== Additional Resources

* Blog: https://sease.io/2022/01/apache-solr-neural-search.html
* Blog: https://sease.io/2022/01/apache-solr-neural-search-knn-benchmark.html
