= Expression Value Source Parser
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

The `ExpressionValueSourceParser` allows you to configure named JavaScript expressions in your `solrconfig.xml` that can be referenced in function queries.
This provides a powerful way to define reusable expressions that can be combined and referenced in queries.
The expressions are based on the Lucene Expressions module, which you can learn more about in the {lucene-javadocs}/expressions/org/apache/lucene/expressions/js/package-summary.html[Lucene Expressions documentation].

== Configuration

To use the `ExpressionValueSourceParser`, you need to configure it in your `solrconfig.xml` file:

[source,xml]
----
<valueSourceParser name="expr" class="solr.ExpressionValueSourceParser">
  <lst name="expressions">
    <str name="sin1">sin(1)</str>
    <str name="cos_sin1">cos(sin1)</str>
    <str name="sqrt_int1_i">sqrt(int1_i)</str>
    <str name="one_plus_score">1 + score</str>
  </lst>
</valueSourceParser>
----

The configuration consists of:

* A `name` attribute that defines the parser name to be used in queries (e.g., `expr`)
* A `class` attribute that specifies the implementation class (`solr.ExpressionValueSourceParser`)
* A list of named expressions in the `expressions` element, where each expression is defined with a name and a JavaScript expression

The parser binds the special name `score` to the document's score.

== Using Expressions

Once configured, you can use the named expressions in xref:function-queries.adoc[function queries] in any place that function queries are supported.
This first example shows it used for sorting:

[source,text]
----
q=*:*&sort=expr(sqrt_int1_i) desc
----

This example shows it in the field list to return calculated values:

[source,text]
----
fl=id,expr(one_plus_score),score
----



== Score Manipulation with Expressions

A particularly powerful feature of the Expression Value Source Parser is the ability to reference the document score in expressions.
This allows for convenient score manipulation and boosting in a more natural way.
For example, you can create expressions that combine the score with other factors:

[source,xml]
----
<valueSourceParser name="expr" class="solr.ExpressionValueSourceParser">
  <lst name="expressions">
    <str name="popularity_and_score">sqrt(popularity) * score</str>
  </lst>
</valueSourceParser>
----

Using expressions to manipulate scores is more efficient than using the "query" function query when you need to reference the score.
The "query" function effectively executes the score calculation twice internally, whereas expressions can reference the score directly.

== Expression Features

* Expressions can reference other expressions defined in the same parser
* Expressions can reference field values directly by field name
* Expressions can use the document's score
* Expressions support standard JavaScript math operations and functions
* The parser automatically detects and prevents circular references in expressions

== Example

This example shows how to configure expressions that build on each other:

[source,xml]
----
<valueSourceParser name="expr" class="solr.ExpressionValueSourceParser">
  <lst name="expressions">
    <str name="sqrt_popularity">sqrt(popularity)</str>
    <str name="log_price">log(price)</str>
    <str name="boost_formula">sqrt_popularity / log_price</str>
  </lst>
</valueSourceParser>
----

You can then use these expressions in queries:

[source,text]
----
q=title:solr&sort=expr(boost_formula) desc
----
