title: Fields configured in the schema to be neither indexed or stored will now be
  quietly ignored by Solr when Documents are added. The example schema has a comment
  explaining how this can be used to ignore any "unknown" fields.
type: added
authors:
- name: Will Johnson
- name: hossman
links:
- name: SOLR-217
  url: https://issues.apache.org/jira/browse/SOLR-217
