title: allow configuration of a limit of the number of searchers that can be warming
  in the background. This can be used to avoid out-of-memory errors, or contention
  caused by more and more searchers warming in the background. An error is thrown
  if the limit specified by maxWarmingSearchers in solrconfig.xml is exceeded.
type: added
authors:
- name: yonik
links:
- name: SOLR-91
  url: https://issues.apache.org/jira/browse/SOLR-91
