title: ConfigSet handler now supports overrides on existing configsets.
type: added
authors:
- name: Tomás Fernández Löbbe
links:
- name: SOLR-10391
  url: https://issues.apache.org/jira/browse/SOLR-10391
