title: solr.hdfs.buffer.size can be configured for HdfsBackupRepository for better
  performance
type: changed
authors:
- name: Tim Owen
links:
- name: SOLR-13029
  url: https://issues.apache.org/jira/browse/SOLR-13029
