title: SpellChecker accuracy configuration is not applied for FileBasedSpellChecker.
  Apply it for FileBasedSpellChecker and IndexBasedSpellChecker both.
type: fixed
authors:
- name: shalin
links:
- name: SOLR-616
  url: https://issues.apache.org/jira/browse/SOLR-616
