title: Expose sort_values returned by QueryComponent in SolrJ's QueryResponse
type: added
authors:
- name: Dan Rosher
- name: shalin
links:
- name: SOLR-611
  url: https://issues.apache.org/jira/browse/SOLR-611
