title: New &lt;lockType&gt; configuration setting in &lt;mainIndex&gt; and &lt;indexDefaults&gt;
  blocks supports all Lucene builtin LockFactories. 'single' is recommended setting,
  but 'simple' is default for total backwards compatibility.
type: added
authors:
- name: Will Johnson
- name: hossman
links:
- name: SOLR-240
  url: https://issues.apache.org/jira/browse/SOLR-240
