title: 'DIH: Allow configurable locales through a locale attribute in fields for NumberFormatTransformer.'
type: added
authors:
- name: Stefan Oestreicher
- name: shalin
links:
- name: SOLR-700
  url: https://issues.apache.org/jira/browse/SOLR-700
