title: Added support for properties in configuration files. Properties can be specified
  in solr.xml and can be used in solrconfig.xml and schema.xml
type: added
authors:
- name: Henri Biestro
- name: hossman
- name: ryan
- name: shalin
links:
- name: SOLR-716
  url: https://issues.apache.org/jira/browse/SOLR-716
