= Configuration Guide
:page-children: configuration-files, \
    property-substitution, \
    core-discovery, \
    configuring-solr-xml, \
    configuring-solrconfig-xml, \
    configuration-apis, \
    config-sets, \
    resource-loading, \
    solr-plugins
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[.lead]
This section covers configuration files and options for customizing your Solr installation.

****
<<configuration-files.adoc#,*Solr Configuration Files*>>: Solr's major configuration files.
****

****
<<property-substitution.adoc#,*Property Substitution in Configuration Files*>>: Provide property values at startup or in shared property files.
****

****
<<core-discovery.adoc#,*Core Discovery*>>: Placement of `core.properties` and available property options.
****

****
<<configuring-solr-xml.adoc#,*Configuring solr.xml*>>: Define `solr.xml`, including the acceptable parameters for the `solr.xml` file.
****

****
<<configuring-solrconfig-xml.adoc#,*Configuring solrconfig.xml*>>: Options for the main configuration file for Solr, `solrconfig.xml`.

// This pulls the sub-section list from the child page to reduce errors
include::configuring-solrconfig-xml.adoc[tag=solrconfig-sections]
****

****
<<configuration-apis.adoc#,*Configuration APIs*>>: Configuration APIs available.

// This pulls the sub-section list from the child page to reduce errors
include::configuration-apis.adoc[tag=configapi-sections]
****

****
<<config-sets.adoc#,*Configsets*>>: Use configsets to avoid duplicating effort when defining a new core.
****

****
<<resource-loading.adoc#,*Resource Loading*>>: Describes how word lists, model files, and other related data are resolved by the components that need them.
****

****
<<solr-plugins.adoc#,*Solr Plugins*>>: Solr's plugin framework for add-on functionality.

// This pulls the sub-section list from the child page to reduce errors
include::solr-plugins.adoc[tag=plugin-sections]
****
