= Getting Started
:page-children: introduction, \
    solr-concepts, \
    solr-tutorial, \
    solr-admin-ui, \
    about-this-guide
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[.lead]
Solr makes it easy for programmers to develop sophisticated, high-performance search applications with advanced features.

This section introduces you to the basic Solr architecture and features to help you get up and running quickly.
It covers the following topics:

****
<<introduction.adoc#,*Introduction to Solr*>>: Short introduction to Solr's primary features.
****

****
<<solr-concepts.adoc#,*Solr Concepts*>>: Beginner information on Solr and information retrieval concepts.

// This pulls the sub-section list from the child page to reduce errors
include::solr-concepts.adoc[tag=concept-sections]
****

****
<<solr-tutorial.adoc#,*Solr Tutorial*>>: A multi-exercise tutorial that covers the main concepts of indexing and querying Solr.
****

****
<<solr-admin-ui.adoc#,*Solr Admin UI*>>: Solr's Web-based interface for administering Solr.
****

****
<<about-this-guide.adoc#,*About this Guide*>>: How to use this Reference Guide.
****
