= Apache Solr Reference Guide
:page-children: getting-started, \
    deployment-guide, \
    configuration-guide, \
    schema-indexing-guide, \
    query-guide, \
    solr-upgrade-notes, \
    how-to-contribute
:page-notitle:
:page-show-toc: false
:page-layout: home
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// This jumbotron is in a sidebar-style block instead of an open block because
// an open block uses a different template that we rely on for other uses.
// See also src/_templates/open.html.slim for the open block template.
[.jumbotron]
****
[.lead-homepage]
Welcome to Apache Solr(TM), the open source solution for search and analytics.

Solr is the fast open source search platform built on Apache Lucene(TM) that provides scalable indexing and search, as well as faceting, hit highlighting and advanced analysis/tokenization capabilities. Solr and Lucene are managed by the http://www.apache.org/[Apache Software Foundation].

This Reference Guide is the official Solr documentation, written and published by Lucene/Solr committers.

++++
<p><a class="btn btn-home btn-lg" href="https://solr.apache.org/downloads.html" role="button">Download Solr</a></p>
++++
****

The Guide includes the following sections:

[.container]
--
.Getting Started with Solr
[sidebar.col]
****

The *<<getting-started.adoc#,Getting Started>>* section guides you through the installation and setup of Solr. A detailed tutorial for first-time users shows many of Solr's features.

****
--

--

'''

--

--
.Deployment Guide
[sidebar.col]
****

*<<deployment-guide.adoc#,Deployment Guide>>*

This section includes information about installing Solr, taking it to production and how to run it in HDFS or AWS.

*<<solr-upgrade-notes.adoc#,Solr Upgrade Notes>>*: Notes for upgrading between minor versions and migrating to the next major version.
****

.Configuration Guide
[sidebar.col]
****
*<<configuration-guide.adoc#,Configuration Guide>>*

Covers tuning Solr's configuration files for your use case. Includes sections on securing Solr, scaling Solr, and integrating plugins.
****
--

--

'''

--

--
.Schema and Indexing Guide
[sidebar.col]
****

*<<schema-indexing-guide.adoc#,Schema and Indexing Guide>>*

Covers all aspects of configuring Solr's schema and indexing documents.
****

.Query Guide
[sidebar.col]
****
*<<query-guide.adoc#,Query Guide>>*

This section presents an overview of the search process in Solr. It describes the main components used in searches, including request handlers, query parsers, and response writers. It lists the query parameters that can be passed to Solr, and it describes features such as boosting and faceting, which can be used to fine-tune search results.

****
--
