= Major Changes in Solr 9
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr 9.0 is a major new release of Solr.

This page highlights the biggest changes, including new features you may want to be aware of, and changes in default behavior and deprecated features that have been removed.

== Solr 9 Upgrade Planning

Before starting an upgrade to Solr 9, please take the time to review all information about changes from the version you are currently on up to Solr 9.

You should also consider all changes that have been made to Solr in any version you have not upgraded to already. For example, if you are currently using Solr 8.1, you should review changes made in all subsequent 8.x releases in addition to changes for 9.0.

A thorough review of the list in Major Changes in Earlier 8.x Versions as well as the {solr-javadocs}/changes//Changes.html[CHANGES.txt] in your Solr instance will help you plan your migration to Solr 9.

=== Upgrade Prerequisites

* LUCENE-8738: Move to Java 11 as minimum Java version.

* Upgrade all collections in `stateFormat=1` to `stateFormat=2` *before* upgrading to Solr 9, as Solr 9 does not support the older format and no longer supports migrating collections from the older format to the current format (previously known as stateFormat=2).
Upgrade is to be done using Collection API MIGRATESTATEFORMAT action using a previous version of Solr.
See for example https://solr.apache.org/guide/8_8/cluster-node-management.html#migratestateforma[Solr 8.8 Ref Guide].
// Can't link directly to .adoc file, need to link to 8.something ref guide as MIGRATESTATEFORMAT no longer exists in 9.0.

* SOLR-12823: Remove `/clusterstate.json` support, i.e., support for collections created with `stateFormat=1` as well as support for Collection API MIGRATESTATEFORMAT action.
Also removes support for cluster property `legacyCloud` (as if always false now).

* If you're using a SolrJ CloudClient to connect to your Solr cluster, you must be using SolrJ version 8.10 or higher (8.x) when upgrading your SolrCloud from 8.x to 9.x.
Otherwise, SolrJ will not be able to connect to the cluster once it has upgraded to Solr 9.
Once you have upgraded all Solr clusters that the client is connecting to, you can upgrade the SolrJ client to 9.x.

* If you're using Solr in standalone mode with the <<query-elevation-component.adoc#,Query Elevation Component>> with it's elevation file in the data directory, you'll have to move it to the <<config-sets.adoc#,Configset>> instead.
The only reason QEC supported the data directory was to support loading its changes on a commit instead of a more expensive core reload.
That feature now works from the configset dir too.
SolrCloud doesn't support that but may sometime.

=== Rolling Upgrades

* SOLR-14702: All references to "master" and "slave" were replaced in the code with "leader" and "follower".
This includes API calls for the replication handler and metrics.
For rolling upgrades into 9.0, you need to be on Solr version 8.7 or greater. Some metrics also changed, alerts and  monitors on Solr KPIs that mention "master" or "slave" will also now be "leader" and "follower"

=== Reindexing After Upgrade

In Solr 8, it's possible to add docValues to a schema without re-indexing via `UninvertDocValuesMergePolicy`, an advanced/expert utility.
Due to changes in Lucene 9, that isn't possible any more; the component was removed.
If re-indexing is too onerous, use this mechanism in Solr 8.

=== Solr Binary Release `dist/` Directory

The `dist/` directory in the Solr binary release has been removed as of Solr 9.0.

* The `solr-core` and `solr-solrj` jars can be found under `server/solr-webapp/webapp/WEB-INF/lib/`.
* The Solr module jars can be found in `modules/<module-name>/lib`, packaged individually for each module.
* The `solrj-deps` (SolrJ Dependencies) are no longer separated out from the other Server jars.
Please refer to the SolrJ Maven artifact to see the exact dependencies you need to include from `server/solr-webapp/webapp/WEB-INF/lib/` and `server/lib/ext/` if you are loading in SolrJ manually.
If you plan on using SolrJ as a JDBC driver, please refer to the <<sql-query.adoc#generic-clients,JDBC documentation>>.

== Solr 9.0 Raw Notes

_(raw; not yet edited)_


* SOLR-13671: Allow 'var' keyword in Java sources

* SOLR-12055 introduces async logging by default. There's a small window where log messages may be lost in the event of some hard crash.
Switch back to synchronous logging if this is unacceptable, see comments in the log4j2 configuration files (log4j2.xml by default).

* SOLR-13323: The unused package org.apache.solr.internal.csv.writer and associated classes/tests that were easily confused with but not used by org.apache.solr.response.CSVWriter (or any other code) have been removed

* SOLR-13854, SOLR-13858: SolrMetricProducer / SolrInfoBean APIs have changed and third-party components that implement these APIs need to be updated.

* SOLR-14344: Remove Deprecated HttpSolrClient.RemoteSolrException and HttpSolrClient.RemoteExcecutionException.
All the usages are replaced by BaseHttpSolrClient.RemoteSolrException and BaseHttpSolrClient.RemoteExcecutionException.

* SOLR-15409: Zookeeper client libraries upgraded to 3.7.0, which may not be compatible with your existing server installations

* SOLR-15809: Get rid of blacklist/whitelist terminology. JWTAuthPlugin parameter `algWhitelist` is now `algAllowlist`. The old parameter will still
  work in 9.x. Environment variables `SOLR_IP_WHITELIST` and `SOLR_IP_BLACKLIST` are no longer supported, but replaced with `SOLR_IP_ALLOWLIST` and `SOLR_IP_DENYLIST`.

* SOLR-11623: Every request handler in Solr now implements PermissionNameProvider. Any custom or 3rd party request handler must also do this

* SOLR-14142: Jetty low level request-logging in NCSA format is now enabled by default, with a retention of 3 days worth of logs.
  This may require some more disk space for logs than was the case in 8.x. See Reference Guide chapter "Configuring Logging" for how to change this.

* SOLR-15944: The Tagger's JSON response format now always uses an object/map to represent each tag instead of an array.

* SOLR-15842: Async responses for backups now correctly aggregate and return information.
In previous versions there was a field returned in async backup status responses, `Response`. This has now been renamed to `msg`, to better fit other collections API responses.
The `response` field is now a map, containing information about the backup (`startTime`, `indexSizeMB`, `indexFileCount`, etc.).

* SOLR-15884: In Backup request responses, the `response` key now uses a map to return information instead of a list.
This is only applicable for users returning information in JSON format, which is the default behavior.

* SOLR-14660: HDFS storage support has been moved to a module. Existing Solr configurations do not need any HDFS-related
changes, however the module needs to be installed - see <<solr-on-hdfs.adoc#,Running Solr on HDFS>>.

* SOLR-15097: JWTAuthPlugin has been moved to a module. Users need to add the module to classpath. The plugin has also
  changed package name to `org.apache.solr.security.jwt`, but can still be loaded as shortform `class="solr.JWTAuthPlugin"`.

== New Features & Enhancements

* Replica placement plugins

* Rate limiting and task management

* Certificate Auth Plugin

* SQL Query interface in UI

== Configuration and Default Parameter Changes

* SOLR-7530: TermsComponent's JSON response format was changed so that "terms" property carries per field arrays by default regardless of distrib, terms.list, terms.ttf parameters.
This affects JSON based response format but not others

* SOLR-14036: Implicit /terms handler now returns terms across all shards in SolrCloud instead of only the local core.
Users/apps may be assuming the old behavior.
A request can be modified via the standard distrib=false param to only use the local core receiving the request.

* SOLR-13783: In situations where a NamedList must be output as plain text, commas between key-value pairs will now be followed by a space (e.g., {shape=square, color=yellow} rather than {shape=square,color=yellow}) for consistency with other `java.util.Map` implementations based on `AbstractMap`.

* SOLR-11725: JSON aggregations uses corrected sample formula to compute standard deviation and variance.
The computation of stdDev and variance in JSON aggregation is same as StatsComponent.

* SOLR-14012: unique and hll aggregations always returns long value irrespective of standalone or solcloud

* SOLR-11775: Return long value for facet count in Json Facet module irrespective of number of shards

* SOLR-15276: V2 API call to look up async request status restful style of "/cluster/command-status/1000" instead of "/cluster/command-status?requestid=1000".

* SOLR-14972: The default port of prometheus exporter has changed from 9983 to 8989, so you may need to adjust your configuration after upgrade.

* SOLR-15471: The language identification "whitelist" configuration is now an "allowlist" to better convey the meaning of the property

* SOLR-12891: MacroExpander will no longer will expand URL parameters inside of the 'expr' parameter (used by streaming expressions).
Additionally, users are advised to use the 'InjectionDefense' class when constructing streaming expressions that include user supplied data to avoid risks similar to SQL injection.
The legacy behavior of expanding the 'expr' parameter can be reinstated with -DStreamingExpressionMacros=true passed to the JVM at startup

* SOLR-13324: URLClassifyProcessor#getCanonicalUrl now throws MalformedURLException rather than hiding it.
Although the present code is unlikely to produce such an exception it may be possible in future changes or in subclasses.
Currently this change should only effect compatibility of custom code overriding this method.

* SOLR-14510: The `writeStartDocumentList` in `TextResponseWriter` now receives an extra boolean parameter representing the "exactness" of the `numFound` value (exact vs approximation).
Any custom response writer extending `TextResponseWriter` will need to implement this abstract method now (instead previous with the same name but without the new boolean parameter).

* SOLR-15259: hl.fragAlignRatio now defaults to 0.33 to be faster and maybe looks nicer.

* SOLR-9376: The response format for field values serialized as raw XML (via the `[xml]` raw value DocTransformer
and `wt=xml`) has changed. Previously, values were dropped in directly as top-level child elements of each `<doc>`,
obscuring associated field names and yielding inconsistent `<doc>` structure. As of version 9.0, raw values are
wrapped in a `<raw name="field_name">[...]</raw>` element at the top level of each `<doc>` (or within an enclosing
`<arr name="field_name"><raw>[...]</raw></arr>` element for multi-valued fields). Existing clients that parse field
values serialized in this way will need to be updated accordingly.

* SOLR-9575: Solr no longer requires a `solr.xml` in `$SOLR_HOME`. If one is not found, Solr will instead use the default one from `$SOLR_TIP/server/solr/solr.xml`. You can revert to the pre-9.0 behaviour by setting environment variable `SOLR_SOLRXML_REQUIRED=true` or system property `-Dsolr.solrxml.required=true`. Solr also does not require a `zoo.cfg` in `$SOLR_HOME` if started with embedded zookeeper.

* SOLR-12901: Highlighting: hl.method=unified is the new default.  Use hl.method=original
  to switch back if needed.

=== solr.xml maxBooleanClauses now enforced recursively

Lucene 9.0 has additional safety checks over previous versions that impact how the `solr.xml` global `<<configuring-solr-xml#global-maxbooleanclauses,maxBooleanClauses>>` option is enforced.

In previous versions of Solr, this option was a hard limit on the number of clauses in any `BooleanQuery` object - but it was only enforced for the _direct_ clauses.
Starting with Solr 9, this global limit is now also enforced against the total number of clauses in a _nested_ query structure.

Users who upgrade from prior versions of Solr may find that some requests involving complex internal query structures (Example: long query strings using `edismax` with many `qf` and `pf` fields that include query time synonym expansion) which worked in the past now hit this limit and fail.

User's in this situation are advised to consider the complexity f their queries/configuration, and increase the value of `<<configuring-solr-xml#global-maxbooleanclauses,maxBooleanClauses>>` if warranted.

=== Log4J configuration & Solr MDC values

link:http://www.slf4j.org/apidocs/org/slf4j/MDC.html[MDC] values that Solr sets for use by Logging calls (such as the collection name, shard name, replica name, etc...) have been modified to now be "bare" values, with out the special single character prefixes that were included in past version.
For example: In 8.x Log messages for a collection named "gettingstarted" would have an MDC value with a key `collection` mapped to a value of `c:gettingstarted`, in 9.x the value will simply be `gettingstarted`.

Solr's default `log4j2.xml` configuration file has been modified to prepend these same prefixes to MDC values when included in Log messages as part of the `<PatternLayout/>`.
Users who have custom logging configurations that wish to ensure Solr 9.x logs are consistently formatted after upgrading will need to make similar changes to their logging configuration files.  See  link:https://issues.apache.org/jira/browse/SOLR-15630[SOLR-15630] for more details.


=== base_url removed from stored state

If you're able to upgrade SolrJ to 8.8.x for all of your client applications, then you can set `-Dsolr.storeBaseUrl=false` (introduced in Solr 8.8.1) to better align the stored state in Zookeeper with future versions of Solr; as of Solr 9.x, the `base_url` will no longer be persisted in stored state.
However, if you are not able to upgrade SolrJ to 8.8.x for all client applications, then you should set `-Dsolr.storeBaseUrl=true` so that Solr will continue to store the `base_url` in Zookeeper.
For background, see: SOLR-12182 and SOLR-15145.

Support for the `solr.storeBaseUrl` system property will be removed in Solr 10.x and `base_url` will no longer be stored.

* Solr's distributed tracing no longer incorporates a special `samplePercentage` SolrCloud cluster property.
Instead, consult the documentation for the tracing system you use on how to sample the traces.
Consequently, if you use a Tracer at all, you will always have traces and thus trace IDs in logs.
What percentage of them get reported to a tracing server is up to you.

* JaegerTracerConfigurator no longer recognizes any configuration in solr.xml.
  It is now completely configured via System properties and/or Environment variables as documented by Jaeger.

=== Schema Changes

* `LegacyBM25SimilarityFactory` has been removed.

* SOLR-13593 SOLR-13690 SOLR-13691: Allow to look up analyzer components by their SPI names in field type configuration.

=== Authentication & Security Changes

* The property `blockUnknown` in the BasicAuthPlugin and the JWTAuthPlugin now defaults to `true`.
This change is backward incompatible.
If you need the pre-9.0 default behavior, you need to explicitly set `blockUnknown:false` in `security.json`.

* The allow-list defining allowed URLs for the `shards` parameter is not in the `shardHandler` configuration anymore. It is defined by the `allowUrls` top-level property of the `solr.xml` file. For more information, see <<configuring-solr-xml.adoc#allow-urls, Format of solr.allowUrls>> documentation.

* SOLR-13985: Solr's Jetty now binds to localhost network interface by default for better out of the box security.
Administrators that need Solr exposed more broadly can change the SOLR_JETTY_HOST property in their Solr include (solr.in.sh/solr.in.cmd) file.

* SOLR-14147: Solr now runs with the java security manager enabled by default. Administrators that need to run Solr with Hadoop will need to disable this feature by setting SOLR_SECURITY_MANAGER_ENABLED=false in the environment or in one of the Solr init scripts. Other features in Solr could also break. (Robert Muir, marcussorealheis)

* SOLR-14118: Solr embedded zookeeper only binds to localhost by default.
This embedded zookeeper should not be used in production.
If you rely upon the previous behavior, then you can change the clientPortAddress in solr/server/solr/zoo.cfg

=== Module Changes

* **SOLR-15917: "Contrib modules" have been renamed to "Modules", and have been moved from the `contrib/` to `modules/`.**
Use of these modules remains the same, except for the changes listed below.

* SOLR-15916: `dist/` is no longer provided in the binary release.
All module jars are now provided under `modules/<name>/lib`, including the module jar and all dependency jars.
Please update your `<lib>` entries in your `solrconfig.xml` to use this new location.
More information can be found in the <<libs.adoc#lib-directives-in-solrconfig,Libs documentation>>.

* SOLR-14067: `StatelessScriptUpdateProcessorFactory` moved to `modules/scripting` package instead of shipping as part of Solr, due to security concerns.
Renamed to ScriptUpdateProcessorFactory for simpler name.

* SOLR-15121: `XSLTResponseWriter` moved to `modules/scripting` package instead
of shipping as part of Solr, due to security concerns.

* SOLR-14926: `modules/clustering` back and rewritten

* SOLR-14912: Cleaned up solr-extraction module to produce solr-extraction-* jar (instead of solr-cell-*). (Dawid Weiss)

* SOLR-15924: Extra lucene libraries used in modules are no longer packaged in `lucene-libs/` under module directories in the binary release.
Instead, these libraries will be included with all other module dependencies in `lib/`.

* SOLR-15954: The prometheus-exporter is no longer packaged as a Solr module. It can be found under `solr/prometheus-exporter/`.

* SOLR-15914: Solr modules (formerly known as contribs) can now easily be enabled by an environment variable (e.g. in `solr.in.sh` or `solr.in.cmd`) or as a system property (e.g. in `SOLR_OPTS`). Example: `SOLR_MODULES=extraction,ltr`.

== Deprecations & Removed Features

The following list of features have been permanently removed from Solr:

* SOLR-14656: Autoscaling framework removed.
This includes:
** Autoscaling, policy, triggers etc.
** withCollection handling (SOLR-14964)
** UTILIZENODE command
** Sim framework
** Suggestions tab in UI
** Reference guide pages for autoscaling
** autoAddReplicas feature

* SOLR-14783: Data Import Handler (DIH) has been removed from Solr.
The community package is available at: https://github.com/rohitbemax/dataimporthandler

* SOLR-14792: VelocityResponseWriter has been removed from Solr.
This encompasses all previous included `/browse` and `wt=velocity` examples.
This feature has been migrated to an installable package at https://github.com/erikhatcher/solr-velocity

* SOLR-13817: Legacy SolrCache implementations (LRUCache, LFUCache, FastLRUCache) have been removed.
Users have to modify their existing configurations to use CaffeineCache instead. (ab)

* CDCR

* Solr's blob store
** SOLR-14654: plugins cannot be loaded using "runtimeLib=true" option. Use the package manager to use and load plugins

* Metrics History

* SOLR-15470: The binary distribution no longer contains test-framework jars.

* SOLR-15203: Remove the deprecated `jwkUrl` in favour of `jwksUrl` when configuring JWT authentication.

* SOLR-12847: maxShardsPerNode parameter has been removed because it was broken and inconsistent with other replica placement strategies.
Other relevant placement strategies should be used instead, such as autoscaling policy or rules-based placement.

* SOLR-14092: Deprecated BlockJoinFacetComponent and BlockJoinDocSetFacetComponent are removed.
Users are encouraged to migrate to uniqueBlock() in JSON Facet API.  (Mikhail Khludnev)

* SOLR-13596: Deprecated GroupingSpecification methods are removed.

* SOLR-11266: default Content-Type override for JSONResponseWriter from `_default` configSet is removed.
Example has been provided in `sample_techproducts_configs` to override content-type.

* `min_rf` deprecated in 7.x

* hl.method=postings highlighter, deprecated in 7.0

* SOLR-15124: Removed three core level admin API endpoints because they are already registered at the node level
where they really belong: /admin/threads, /admin/properties, /admin/logging
