title: PingRequestHandler is now directly configured with a "healthcheckFile" instead
  of looking for the legacy &lt;admin&gt;&lt;healthcheck/&gt;&lt;/admin&gt; syntax.
  Filenames specified as relative paths have been fixed so that they are resolved
  against the data dir instead of the CWD of the java process.
type: other
authors:
- name: hossman
links:
- name: SOLR-1258
  url: https://issues.apache.org/jira/browse/SOLR-1258
