title: 'Maven configuration: Excluded transitive stax:stax-api dependency from org.codehaus.woodstox:wstx-asl
  dependency.'
type: other
authors:
- name: David Smiley
- name: Steve Rowe
links:
- name: SOLR-2756
  url: https://issues.apache.org/jira/browse/SOLR-2756
