title: 'Example schemaless solr config files can lead to invalid tlog replays: when
  updates are buffered, update processors ordered before DistributedUpdateProcessor,
  e.g. field normalization, are never run.'
type: fixed
authors:
- name: Steve Rowe
links:
- name: SOLR-9883
  url: https://issues.apache.org/jira/browse/SOLR-9883
