title: Allow custom configuration of Jetty's SecureRequestCustomizer
type: other
authors:
- name: Tomás Fernández Löbbe
links:
- name: SOLR-16735
  url: https://issues.apache.org/jira/browse/SOLR-16735
