title: 'Maven config: make the org.slf4j:slf4j-api dependency transitive (i.e., not
  optional) in all modules in which it''s a dependency, including solrj, except for
  the WAR, where it will remain optional.'
type: fixed
authors:
- name: Uwe Schindler
- name: Steve Rowe
links:
- name: SOLR-5950
  url: https://issues.apache.org/jira/browse/SOLR-5950
