= Securing Solr
:page-children: authentication-and-authorization-plugins, \
    audit-logging, \
    enabling-ssl, \
    zookeeper-access-control, \
    security-ui
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

[WARNING]
====
No Solr API, including the Admin UI, is designed to be exposed to non-trusted parties.
Tune your firewall so that only trusted computers and people are allowed access.
Because of this, the project will not regard e.g., Admin UI XSS issues as security vulnerabilities.
However, we still ask you to report such issues in JIRA.
====

When planning how to secure Solr, you should consider which of the available features or approaches are right for you:

== Encryption with TLS (SSL) Certificates

Encrypting traffic to/from Solr and between Solr nodes prevents sensitive data to be leaked out on the network.
TLS is also normally a requirement to prevent credential sniffing when using Authentication.

See the section xref:enabling-ssl.adoc[] for details.

== Authentication and Authorization

Use the xref:security-ui.adoc[] screen in the Admin UI to manage users, roles, and permissions.

See section xref:authentication-and-authorization-plugins.adoc[] to learn how to work with the `security.json` file.

[#securing-solr-auth-plugins]
=== Authentication Plugins

Authentication makes sure you know the identity of your users.
The authentication plugins that ship with Solr are:

// tag::list-of-authentication-plugins[]
[width=100%,cols="1,1",frame=none,grid=none,stripes=none]
|===
| xref:basic-authentication-plugin.adoc[]
| xref:kerberos-authentication-plugin.adoc[]
| xref:jwt-authentication-plugin.adoc[]
| xref:cert-authentication-plugin.adoc[]
| xref:hadoop-authentication-plugin.adoc[]
|
|===
// end::list-of-authentication-plugins[]

=== Authorization Plugins

Authorization makes sure that only users with the necessary roles/permissions can access any given resource.
The authorization plugins that ship with Solr are:

// tag::list-of-authorization-plugins[]
[width=100%,cols="1,1",frame=none,grid=none,stripes=none]
|===
| xref:rule-based-authorization-plugin.adoc[]
| xref:rule-based-authorization-plugin.adoc[External Role Rule-Based Authorization Plugin]
|===
// end::list-of-authorization-plugins[]

== Audit Logging

Audit logging will record an audit trail of incoming reqests to your cluster, such as users being denied access to admin APIs.
Learn more about audit logging and how to implement an audit logger plugin in the section xref:audit-logging.adoc[].

== IP Access Control

Restrict network access to specific hosts, by setting `SOLR_IP_ALLOWLIST`/`SOLR_IP_DENYLIST` via environment variables or in `solr.in.sh`/`solr.in.cmd`.

[source,bash]
----
# Allow IPv4/IPv6 localhost, the 192.168.0.x IPv4 network, and 2000:123:4:5:: IPv6 network.
SOLR_IP_ALLOWLIST="127.0.0.1, [::1], 192.168.0.0/24, [2000:123:4:5::]/64"
# Explicitly deny access to two problematic hosts.
SOLR_IP_DENYLIST="192.168.0.3, 192.168.0.4"
----

== Securing ZooKeeper Traffic

ZooKeeper is a central and important part of a SolrCloud cluster and understanding how to secure
its content is covered in the section xref:zookeeper-access-control.adoc[].

== Network Configuration

// tag::security-network-binding-1[]
Administrators should consider their security setup carefully as an important step in moving to production.
Solr provides a number of features out of the box to meet the security needs of users: authentication and authorization can be configured using a range of security plugins, privacy can be bolstered by enabling SSL/TLS, and (in SolrCloud) ZooKeeper data can be protected with ACL rules to prevent unauthorized reads and writes.

Even if these measures or others are taken, it is strongly recommended that Solr always be protected by a firewall.
Solr is not designed to be exposed on the open internet.

It is also strongly recommended that Solr listen to only those network interfaces that are strictly required.
To prevent administrators from unintentionally exposing Solr more broadly, Solr only listens on the loopback interface ("127.0.0.1") by default.
Most deployments will need to change this value to something less restrictive so that it can be reached from other boxes.
This can be done by setting a `SOLR_JETTY_HOST` value in your environment's "include script" (`solr.in.sh` or `solr.in.cmd`):

[source,bash]
 ----
 SOLR_JETTY_HOST="0.0.0.0"
 ----

The same setting is also available as the `-Dsolr.jetty.host` System Property.

The same is true for the embedded Zookeeper, if it is run with Solr.
By default, the embedded Zookeeper only listens on the loopback interface ("127.0.0.1")
The bind host is controlled via the `SOLR_ZK_EMBEDDED_HOST` value in your environment's "include script" (`solr.in.sh` or `solr.in.cmd`):

[source,bash]
 ----
 SOLR_ZK_EMBEDDED_HOST="0.0.0.0"
 ----

The same setting is also available as the `-Dsolr.zk.embedded.host` System Property.
// end::security-network-binding-1[]
