= Task Management
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr allows users to control their running tasks by monitoring them, specifying tasks as cancellation enabled and allowing
cancellation of the same.

This is achieved using the task management interface.
Currently, this is supported for queries.

== Types of Operations
Task management interface supports the following types of operations:

. List all currently running cancellable tasks.
. Cancel a specific task.
. Query the status of a specific task.



== Listing All Active Cancellable Tasks
To list all the active cancellable tasks currently running, please use the following syntax:

[.dynamic-tabs]
--
[example.tab-pane#v1listalltasks]
====
[.tab-label]*V1 API*

[source,bash]
----
curl -X GET "http://localhost:8983/solr/collectionName/tasks/list"
----
====

[example.tab-pane#v2listalltasks]
====
[.tab-label]*V2 API*

[source,bash]
----
curl -X GET "http://localhost:8983/v2/collections/collName/tasks/list"
----
====
--

=== Sample Response

----
{
  "responseHeader":{
    "status":0,
    "QTime":16},
  "taskList":[
    "0,"q=weight_i:[0+TO+200]&canCancel=true&queryUUID=0",
    "5","q=weight_i:[0+TO+200]&canCancel=true&queryUUID=5",
    "4bcd27bb-0792-4512-a699-532fa7878bd3","q=weight_i:[0+TO+200]&canCancel=true"]}
----

== Cancelling An Active Cancellable Task
To cancel an active task, please use the following syntax:

[.dynamic-tabs]
--
[example.tab-pane#v1cancelalltasks]
====
[.tab-label]*V1 API*

[source,bash]
----
curl -X GET "http://localhost:8983/solr/collectionName/tasks/cancel?queryUUID=5"
----
====

[example.tab-pane#v2cancelalltasks]
====
[.tab-label]*V2 API*

[source,bash]
----
curl -X GET "http://localhost:8983/v2/collections/collName/tasks/cancel?queryUUID=5"
----
====
--

=== Sample Response
==== If the task UUID was found and successfully cancelled:

----
{
  "responseHeader":{
    "status":0,
    "QTime":26},
  "status":"Query with queryID 5 cancelled successfully",
  "responseCode":200}
----

==== If the task UUID was not found

----
{
  "responseHeader":{
    "status":0,
    "QTime":24},
  "status":"Query with queryID 5 not found",
  "responseCode":404}
----

== Check Status of a Specific Task
To check the status of a specific task, please use the following syntax:

[.dynamic-tabs]
--
[example.tab-pane#v1checksingletask]
====
[.tab-label]*V1 API*

[source,bash]
----
curl -X GET "http://localhost:8983/solr/collectionName/tasks/list?taskUUID=5"
----
====

[example.tab-pane#v2checksingletask]
====
[.tab-label]*V2 API*

[source,bash]
----
curl -X GET "http://localhost:8983/v2/collections/collName/tasks/list?taskUUID=5"
----
====
--

=== taskUUID Parameter
`taskUUID` parameter can be used to specify a task UUID whose status can be checked.

=== Sample Response

----
{
  "responseHeader":{
    "status":0,
    "QTime":16},
  "taskStatus":"id:5, status: active"}
----
