title: All example config sets now explicitly use the ManagedIndexSchemaFactory instead
  of ClassicIndexSchemaFactory. This means that the Schema APIs ( /&lt;collection&gt;/schema
  ) are enabled by default and the schema is mutable. The schema file will be called
  managed-schema
type: other
authors:
- name: Uwe Schindler
- name: shalin
- name: Varun Thacker
links:
- name: SOLR-8131
  url: https://issues.apache.org/jira/browse/SOLR-8131
