title: Collections created from _default configset will now be associated with a configset
  with a suffix .AUTOCREATED. For example, a new collection "mycollection", created
  without specifying a configset name, will use the _default configset and the associated
  configset name will be "mycollection.AUTOCREATED". If this collection is deleted
  and re-created, the autocreated configset will be left behind and will be re-used
  for the re-created collection
type: other
authors:
- name: Ishan Chattopadhyaya
- name: Abhishek Kumar Singh
links:
- name: SOLR-11624
  url: https://issues.apache.org/jira/browse/SOLR-11624
