title: Remove reopenReaders attribute from 'IndexConfig in SolrConfig' page in ref
  guide.
type: other
authors:
- name: shalin
links:
- name: SOLR-12099
  url: https://issues.apache.org/jira/browse/SOLR-12099
