title: The "config-read" permission has been fixed to properly allow access to `/solr/admin/configs?action=LIST`
type: fixed
authors:
- name: Jon Senchyna
- name: Eric Pugh
links:
- name: SOLR-15626
  url: https://issues.apache.org/jira/browse/SOLR-15626
