title: new UI and example solrconfig files point to Reference Guide for Solr Query
  Syntax instead of the wiki.
type: other
authors:
- name: Marius Grama
links:
- name: SOLR-8713
  url: https://issues.apache.org/jira/browse/SOLR-8713
