title: deprecate AdminHandlers, Clean up solrconfig.xml of unnecessary plugin definitions,
  implicit registration of /replication, /get and /admin/* handlers
type: other
authors:
- name: Noble Paul
links:
- name: SOLR-6792
  url: https://issues.apache.org/jira/browse/SOLR-6792
