= Major Changes in Solr 11
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Solr 11.0 is a major new release of Solr.

This page highlights the most important changes including new features and changes in default behavior as well as previously deprecated features that have now been removed.

== Solr 11 Upgrade Planning

Before starting an upgrade to this version of Solr, please be sure to review all information about changes from the version you are currently on up to this one, to include the minor version number changes as well.

== Index Sorting Configuration

Index sorting can now be configured directly with the xref:configuration-guide:index-segments-merging.adoc#indexsort[`<indexSort>`] element in the `<indexConfig>` section of `solrconfig.xml`, instead of indirectly through a `SortingMergePolicyFactory`.

As a result, `SortingMergePolicyFactory` (and the underlying `SortingMergePolicy`) are now *deprecated*.
Configurations that use `SortingMergePolicyFactory` continue to work, but should migrate to `<indexSort>`:

[source,xml]
----
<indexConfig>
  <indexSort>timestamp_dt desc</indexSort>
</indexConfig>
----

To enable (or change) index sorting on a collection that already has data, use the xref:configuration-guide:coreadmin-api.adoc#coreadmin-resortindex[`RESORTINDEX`] core admin action to re-sort the existing segments; index sorting is not applied to already-written segments automatically on reload.

The related between-segment ordering can be configured with the new xref:configuration-guide:index-segments-merging.adoc#segmentsort[`<segmentSort>`] element.
