= Solr Upgrade Notes
:page-children: major-changes-in-solr-9, \
    major-changes-in-solr-8, \
    major-changes-in-solr-7, \
    major-changes-in-solr-6
:toclevels: 3
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

The following notes describe changes to Solr in recent releases that you should be aware of before upgrading.

These notes highlight the important changes that may impact the largest number of implementations.
It is not a comprehensive list of all changes to Solr in any release.

When planning your Solr upgrade, consider the customizations to
your system and review the {solr-javadocs}/changes/Changes.html[`CHANGES.txt`]
file found in your Solr package.
That file includes all the changes and updates
that may affect your existing implementation.

Detailed steps for upgrading a Solr cluster are in the section xref:deployment-guide:upgrading-a-solr-cluster.adoc[].

// DO NOT ADD MINOR VERSION INFO HERE; see child pages

Zookeeper Credentials support now follows a new paradigm.
Old classes, such as `VMParamsAllAndReadonlyDigestZkACLProvider` and `VMParamsSingleSetCredentialsDigestZkCredentialsProvider`, are deprecated but still supported until at least `10.0`.
Users are encouraged to upgrade to the non-deprecated classes before the next major version release.
Please refer to xref:deployment-guide:zookeeper-access-control.adoc#solr-to-zookeeper-acls-workflow[] for more information.

== Upgrading to 9.0 from 8.x Releases

The upgrade from 8.x to Solr 9.0 introduces several *major* changes that you should be aware of before upgrading.
These changes are described in the section xref:major-changes-in-solr-9.adoc[].
It's strongly recommended that you thoroughly review that section before starting your upgrade.

[NOTE]
If you run in SolrCloud mode and use SolrJ's `CloudSolrClient`, you must first upgrade SolrJ to a version 8.10 or higher before upgrading the cluster to 9.0.

[NOTE]
Rolling upgrades from Solr 8 to Solr 9 require first upgrading the cluster to version 8.7 or newer.

== Upgrading from Pre-8.x Versions

Users upgrading from versions prior to 8.x are strongly encouraged to consult {solr-javadocs}/changes/Changes.html[`CHANGES.txt`] for the details of _all_ changes since the version they are upgrading from.

The upgrade from 7.x to 8.0 introduced several *major* changes that you should be aware of before upgrading.
Please do a thorough review of the section xref:major-changes-in-solr-8.adoc[] before starting your upgrade.

A summary of the significant changes between Solr 6.x and Solr 7.0 is in the section xref:major-changes-in-solr-7.adoc[].
