title: Tests and example configs demonstrating SSL with both server and client certs
type: other
authors:
- name: hossman
links:
- name: SOLR-4394
  url: https://issues.apache.org/jira/browse/SOLR-4394
