# Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements; and to You under the Apache License, Version 2.0.
#
# Filename regex -> password map
# Example any file ending in .doc should use password foobar:
#  .*\.doc = fooBar
#
# Note: Apache Tika 1.1 supports password for .pdf and .docx only, not .doc or other formats
.*\.pdf$ = solrRules
.*\.docx$ = Word2010
