title: Log config name found for collection at info level.
type: other
authors:
- name: Christine Poerschke
- name: Mark Miller
links:
- name: SOLR-5702
  url: https://issues.apache.org/jira/browse/SOLR-5702
