title: Validate the presence of configset before trying to create a collection.
type: fixed
authors:
- name: Anshum Gupta
- name: Mark Miller
links:
- name: SOLR-7038
  url: https://issues.apache.org/jira/browse/SOLR-7038
