title: Passing values for custom Carrot2 fields to Clustering component. The custom
  field mapping are defined using the carrot.custom parameter
type: fixed
authors:
- name: Stanislaw Osinski
links:
- name: SOLR-2940
  url: https://issues.apache.org/jira/browse/SOLR-2940
