title: Configuring the number of contextual snippets used for search results clustering.
  The hl.snippets parameter is now respected by the clustering plugin, can be overridden
  by carrot.summarySnippets if needed
type: fixed
authors:
- name: Stanislaw Osinski
links:
- name: SOLR-2937
  url: https://issues.apache.org/jira/browse/SOLR-2937
