title: Configuring a shardHandlerFactory on the /select requestHandler results in
  HTTP 401 when searching on alias in secured Solr.
type: fixed
authors:
- name: Isabelle Giguere
- name: Jason Gerlowski
- name: Anshum Gupta
- name: Mark Mark Miller
links:
- name: SOLR-14569
  url: https://issues.apache.org/jira/browse/SOLR-14569
