title: Force Calcite's Rel simplify config flag to false to avoid erasing filters
  that are meaningful to Solr, but look like nonsense to Calcite, such as AND'd filters
  on the same multi-valued field
type: fixed
authors:
- name: Timothy Potter
- name: Kiran Chitturi
links:
- name: SOLR-16009
  url: https://issues.apache.org/jira/browse/SOLR-16009
