title: SolrConfig can miss updates from ZooKeeper when deleting and recreating file
  items
type: fixed
authors:
- name: Mike Drob
links:
- name: SOLR-16143
  url: https://issues.apache.org/jira/browse/SOLR-16143
