title: Move the Prometheus Exporter from "solr/modules/prometheus-exporter" to "solr/prometheus-exporter".
type: other
authors:
- name: Houston Putman
links:
- name: SOLR-15954
  url: https://issues.apache.org/jira/browse/SOLR-15954
