title: HdfsUpdateLog does not use configured or new default number of version buckets
  and is hard coded to 256.
type: fixed
authors:
- name: Mark Miller
- name: yonik
- name: Gregory Chanan
links:
- name: SOLR-8857
  url: https://issues.apache.org/jira/browse/SOLR-8857
