title: useColdSearcher control in solrconfig.xml prevents the first searcher from
  being used before it's done warming. This can help prevent thrashing on startup
  when multiple requests hit a cold searcher. The default is "false", preventing use
  before warm. SOLR-77
type: added
authors:
- name: yonik
links:
- name: SOLR-77
  url: https://issues.apache.org/jira/browse/SOLR-77
