title: Fix default solr-exporter-config.xml metrics with incorrect time unit conversions.
type: fixed
authors:
- name: Matthew Biscocho
links:
- name: SOLR-15083
  url: https://issues.apache.org/jira/browse/SOLR-15083
