title: SolrJ CloudSolrClient configured with HTTP URLs will no longer eagerly connect
  to anything.
type: changed
authors:
- name: David Smiley
links:
- name: SOLR-17607
  url: https://issues.apache.org/jira/browse/SOLR-17607
