////
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Solr Source Directories

[benchmark/](benchmark/):: \
Benchmarking module for Solr.

[bin/](bin/):: \
Scripts to startup, manage and interact with Solr instances.

[core/](core/):: \
Base Solr code.

[distribution/](distribution/):: \
Gradle project for building a full release of Solr.

[docker/](docker/)::
Contains a Dockerfile to build a Docker image using the source or binary distribution.
`docker/scripts` contains scripts that the Docker image uses to manage Solr.

[documentation/](documentation/)::
Gradle project to build the JavaDocs site.

[example/](example/)::
Contains example documents and an alternative Solr home
directory containing various examples.

[license/](license/)::
Licenses, notice files and signatures for Solr dependencies.

[modules/](modules/)::
Contains modules to extend the functionality of Solr.

[packaging/](packaging/)::
Gradle project to build the binary release of Solr.

[prometheus-exporter/](prometheus-exporter/)::
Contains a separate application to monitor Solr instances and export Prometheus metrics.

[server/](server/)::
Gradle project that builds the Jetty server to run Solr.

[solr-ref-guide/](solr-ref-guide/)::
The Solr Reference Guide source files including Java examples.

[solrj/](solrj/)::
Solr client code for Java applications.

[test-framework/](test-framework/)::
Solr test framework for internal tests and external tests integrating Solr.

[webapp/](webapp/)::
Admin UI Javascript and supporting assets.
