= Fields
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

Fields are defined in the fields element of a xref:schema-elements.adoc[schema].
Once you have the field types set up, defining the fields themselves is simple.

== Example Field Definition

The following example defines a field named `price` with a type named `float` and a default value of `0.0`; the `indexed` and `stored` properties are explicitly set to `true`, while any other properties specified on the `float` field type are inherited.

[source,xml]
----
<field name="price" type="float" default="0.0" indexed="true" stored="true"/>
----

== Field Properties

Field definitions can have the following properties:

`name`::
+
[%autowidth,frame=none]
|===
s|Required |Default: none
|===
+
The name of the field.
Field names should consist of alphanumeric or underscore characters only and not start with a digit.
This is not currently strictly enforced, but other field names will not have first class support from all components and back compatibility is not guaranteed.
Names with both leading and trailing underscores (e.g., `\_version_`) are reserved.

`type`::
+
[%autowidth,frame=none]
|===
s|Required |Default: none
|===
+
The name of the `fieldType` for this field.
This will be found in the `name` attribute on the `fieldType` definition.
Every field must have a `type`.

`default`::
+
[%autowidth,frame=none]
|===
|Optional |Default: none
|===
+
A default value that will be added automatically to any document that does not have a value in this field when it is indexed.
If this property is not specified, there is no default.

== Optional Field Type Override Properties

Fields can have many of the same properties as field types.
Properties from the table below which are specified on an individual field will override any explicit value for that property specified on the `fieldType` of the field, or any implicit default property value provided by the underlying `fieldType` implementation.
The table below is reproduced from xref:field-type-definitions-and-properties.adoc[], which has more details:

--
include::field-type-definitions-and-properties.adoc[tag=field-params]
--
