title: Allow Passing SSL passwords through environment variables.
type: added
authors:
- name: Mano Kovacs
- name: Michael Suzuki
- name: Mark Miller
links:
- name: SOLR-10307
  url: https://issues.apache.org/jira/browse/SOLR-10307
