title: New _default config set replacing basic_configs and data_driven_schema_configs.
type: added
authors:
- name: Ishan Chattopadhyaya
- name: noble
- name: shalin
- name: hossman
- name: David Smiley
- name: janhoy
- name: Alexandre Rafalovitch
links:
- name: SOLR-10574
  url: https://issues.apache.org/jira/browse/SOLR-10574
