title: Implement read API for autoscaling configuration at /admin/autoscaling or /cluster/autoscaling
  paths.
type: added
authors:
- name: shalin
links:
- name: SOLR-10373
  url: https://issues.apache.org/jira/browse/SOLR-10373
