title: 'Untrusted configsets (ones that are uploaded via unsecured configset API)
  cannot use &lt;lib&gt; directive. Consider enabling authentication/authorization
  so that the uploaded configsets are trusted. Note: If you already have a collection
  using untrusted configset that uses &lt;lib&gt; directive, it will not load after
  upgrading to 8.4. You can re-upload your configset using "bin/solr zk -upconfig
  .." or place your libraries in the classpath and restart Solr.'
type: upgrade_notes
authors: []
links:
- name: SOLR-14071
  url: https://issues.apache.org/jira/browse/SOLR-14071
