title: Tests configure Jetty differently than when running via start.jar
type: fixed
authors:
- name: janhoy
- name: Uwe Schindler
links:
- name: SOLR-13941
  url: https://issues.apache.org/jira/browse/SOLR-13941
