title: Support group.query in multi-shard environment when group.main=true or group.format=simple
type: fixed
authors:
- name: Munendra S N
links:
- name: SOLR-13404
  url: https://issues.apache.org/jira/browse/SOLR-13404
