title: Make contrib/ltr Feature.defaultValue configurable.
type: changed
authors:
- name: Stanislav Livotov
- name: Christine Poerschke
links:
- name: SOLR-13049
  url: https://issues.apache.org/jira/browse/SOLR-13049
