title: Remove deprecated showItems configuration value from solrconfig.xml files
type: other
authors:
- name: Andy Lester
- name: Eric Pugh
links:
- name: SOLR-15886
  url: https://issues.apache.org/jira/browse/SOLR-15886
