title: avoid fetching solrconfig.xml & schema.xml for already cached schema and config
type: changed
authors:
- name: noble
links:
- name: SOLR-16336
  url: https://issues.apache.org/jira/browse/SOLR-16336
