title: Enable warming queries to be managed using Config API
type: changed
authors:
- name: Andy Webb
- name: Eric Pugh
links:
- name: SOLR-9359
  url: https://issues.apache.org/jira/browse/SOLR-9359
