title: Solr Configuration ignores 'mergeFactor' parameter, always uses Lucene default.
type: fixed
authors:
- name: Lance Norskog
links:
- name: SOLR-1580
  url: https://issues.apache.org/jira/browse/SOLR-1580
