title: Add configurable DirectoryProvider so that alternate Directory implementations
  can be specified via solrconfig.xml. The default DirectoryProvider will use NIOFSDirectory
  for better concurrency on non Windows platforms.
type: added
authors:
- name: Mark Miller
- name: TJ Laurenzo
links:
- name: SOLR-465
  url: https://issues.apache.org/jira/browse/SOLR-465
