title: The example solrconfig.xml defaulted to a solr data dir relative to the current
  working directory, even if a different solr home was being used. The new behavior
  changes the default to a zero length string, which is treated the same as if no
  dataDir had been specified, hence the "data" directory under the solr home will
  be used.
type: fixed
authors:
- name: yonik
links:
- name: SOLR-1577
  url: https://issues.apache.org/jira/browse/SOLR-1577
