title: Configurable JDBC settings in JdbcDataSource including optimized defaults for
  read only mode.
type: added
authors:
- name: David Smiley
- name: Glen Newton
- name: shalin
links:
- name: SOLR-812
  url: https://issues.apache.org/jira/browse/SOLR-812
