title: For JWTAuthPlugin, the 'jwkUrl' configuration key is deprecated and may be
  removed later, please use 'jwksUrl' instead. See SOLR-13734.
type: upgrade_notes
authors: []
links:
- name: SOLR-13734
  url: https://issues.apache.org/jira/browse/SOLR-13734
