title: NodeAddedTrigger does not support configuration of replica type hint. A new
  replicaType property has been added to NodeAddTrigger so that new replicas of the
  given type are added. The default value is `NRT`.
type: fixed
authors:
- name: Irena Shaigorodsky
links:
- name: SOLR-13674
  url: https://issues.apache.org/jira/browse/SOLR-13674
