title: Introduce possibility to configure ParseContext in ExtractingRequestHandler/ExtractingDocumentLoader
type: added
authors:
- name: Andriy Binetsky
links:
- name: SOLR-8166
  url: https://issues.apache.org/jira/browse/SOLR-8166
