title: Fix SolrCLI to clean the config directory in case creating a core failed.
type: other
authors:
- name: Jason Gerlowski
links:
- name: SOLR-8246
  url: https://issues.apache.org/jira/browse/SOLR-8246
