name: Solr Script Tests

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/bin-solr-test.yml'
      - 'solr/bin/**'
      - 'solr/packaging/**'
      - 'solr/core/src/java/org/apache/solr/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Solr Script Tests

    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - uses: ./.github/actions/prepare-for-build

    - name: Test the bin/solr script
      run: ./gradlew integrationTests

    - name: Archive logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: logs
        path: solr/packaging/build/test-output
