name: Docker Build & Test

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/docker-test.yml'
      - 'solr/bin/**'
      - 'solr/prometheus-exporter/bin/**'
      - 'solr/docker/**'
      - 'solr/packaging/**'

jobs:
  test:
    name: Build and test Docker image

    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      SOLR_DOCKER_IMAGE_REPO: github-pr/solr
      SOLR_DOCKER_IMAGE_TAG: ${{github.event.number}}
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        java-package: jdk

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Docker image with Gradle
      run: ./gradlew solr:docker:docker

    - name: Run tests on Docker image
      run: ./gradlew solr:docker:testDocker
