name: Docker Build & Test

on:
  pull_request:
    branches:
      - 'main'
      - 'branch_*'
    paths:
      - '.github/workflows/docker-test.yml'
      - 'solr/bin/**'
      - 'solr/prometheus-exporter/bin/**'
      - 'solr/docker/**'
      - 'solr/packaging/**'

jobs:
  test:
    name: Build and test Docker image

    runs-on: ubuntu-latest

    env:
      SOLR_DOCKER_IMAGE_REPO: github-pr/solr
      SOLR_DOCKER_IMAGE_TAG: ${{github.event.number}}
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

    steps:
    # Setup
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
        java-package: jdk
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Install ACL
      run: sudo apt-get install acl
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-docker-${{ hashFiles('versions.lock') }}
        restore-keys: |
          ${{ runner.os }}-gradle-docker-
          ${{ runner.os }}-gradle-
    - name: Build Docker image with Gradle
      run: ./gradlew solr:docker:docker
    - name: Run tests on Docker image
      run: ./gradlew solr:docker:testDocker
