# This test covers TikaServer tests for SolrCell, since crave does not support docker yet.
name: Extraction module tests with Docker

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'solr/modules/extraction/**'

jobs:
  test:
    name: extraction module tests with docker

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: ./.github/actions/prepare-for-build

      - name: Run extraction module tests
        run: ./gradlew --no-daemon solr:modules:extraction:check
