name: SolrJ Tests

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/solrj-test.yml'
      - 'solr/solrj/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run SolrJ Tests

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: ./.github/actions/prepare-for-build

    - name: Test SolrJ module
      run: ./gradlew solr:solrj:test
