title: 'FileSystemConfigSetService: implement the abstraction completely. It could
  be useful for putting ConfigSets on a shared file system.'
type: changed
authors:
- name: Nazerke Seidan
- name: David Smiley
links:
- name: SOLR-15787
  url: https://issues.apache.org/jira/browse/SOLR-15787
