title:
  Migrate GET /config/overlay and GET /config/znodeVersion to JAX-RS.
type: changed
authors:
  - name: Jalaz Kumar
    nick: jaykay12
links:
  - name: SOLR-16396
    url: https://issues.apache.org/jira/browse/SOLR-16396
