title: Remove outmoded and misleading 'bin/solr zk linkconfig' tool.
type: removed
authors:
  - name: Jason Gerlowski
links:
  - name: SOLR-18166
    url: https://issues.apache.org/jira/browse/SOLR-18166
